# Generated by Django 2.1.2 on 2019-06-20 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raptr', '0014_auto_20190619_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docket_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('project_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=8)),
                ('activity_phase', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Legal Review', 'Legal Review'), ('Signed', 'Signed'), ('Closed', 'Closed'), ('Expired', 'Expired')], max_length=8)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('project_title', models.CharField(blank=True, max_length=200, verbose_name='Project Title')),
                ('project_summary', models.TextField(blank=True, max_length=750)),
                ('partner_pi', models.CharField(blank=True, max_length=200, verbose_name='Partner PI')),
                ('partner_contact', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('collaborator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='raptr.Sponsor')),
                ('noaa_pi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='raptr.Contact', verbose_name='NOAA PI')),
            ],
        ),
    ]
